version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:secret@postgres:5432/test?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
